// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxZiX4of-BIWmggshTckW8qEgit0BQMyE',
    appId: '1:98082728281:web:78c9f867af17104f1f4448',
    messagingSenderId: '98082728281',
    projectId: 'chatapp2-1a5b5',
    authDomain: 'chatapp2-1a5b5.firebaseapp.com',
    storageBucket: 'chatapp2-1a5b5.firebasestorage.app',
    measurementId: 'G-Z0B41PYP9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDcP_wNmEGrDa-Qq38H4koLG2rvNYfldE',
    appId: '1:98082728281:android:f259a8afe184e5ff1f4448',
    messagingSenderId: '98082728281',
    projectId: 'chatapp2-1a5b5',
    storageBucket: 'chatapp2-1a5b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFZcDifhRr5JnWWshA4ZbSKRejx6JEcUg',
    appId: '1:98082728281:ios:c4cdbccbb794671c1f4448',
    messagingSenderId: '98082728281',
    projectId: 'chatapp2-1a5b5',
    storageBucket: 'chatapp2-1a5b5.firebasestorage.app',
    androidClientId: '98082728281-c3nkulpc9ha8v3rk00pjggchu21ti8m1.apps.googleusercontent.com',
    iosClientId: '98082728281-s3kleutlnh6o5jsk770bksjn902muhnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFZcDifhRr5JnWWshA4ZbSKRejx6JEcUg',
    appId: '1:98082728281:ios:c4cdbccbb794671c1f4448',
    messagingSenderId: '98082728281',
    projectId: 'chatapp2-1a5b5',
    storageBucket: 'chatapp2-1a5b5.firebasestorage.app',
    androidClientId: '98082728281-c3nkulpc9ha8v3rk00pjggchu21ti8m1.apps.googleusercontent.com',
    iosClientId: '98082728281-s3kleutlnh6o5jsk770bksjn902muhnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxZiX4of-BIWmggshTckW8qEgit0BQMyE',
    appId: '1:98082728281:web:a7b91a988e2419991f4448',
    messagingSenderId: '98082728281',
    projectId: 'chatapp2-1a5b5',
    authDomain: 'chatapp2-1a5b5.firebaseapp.com',
    storageBucket: 'chatapp2-1a5b5.firebasestorage.app',
    measurementId: 'G-ZTKH3BSDPW',
  );

}